CREATE TABLE USUARIO (
	id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	login          VARCHAR(255),
	password       VARCHAR(255),
	email          VARCHAR(255),
	fecha_registro DATE, 
	PRIMARY KEY (id)
);
